spring:
#数据源配置文件 注意，引入aiyuninfo-boot-data之后必须配置数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@108.118.5.1:1521:ora7
    username: michael
    password: carton
#    连接池配置
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 5 
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
custom: 
  datasource: 
    names: sumec3rd
    sumec3rd:  
      url: jdbc:oracle:thin:@108.118.5.1:1521:ora7
      username: sumec3rd
      password: thirdparty
      type: com.zaxxer.hikari.HikariDataSource 
service-config:
  uaa:
    client-id: sumec_its   #客户端ID
    client-secret: sumec_its  #客户端密钥
#    grant-type: client_credentials   #获取token方式，默认client_credentials
#    token-url: http://uaa.aiyuninfo.com/oauth/token  #token授权地址，默认http://uaa.aiyuninfo.com/oauth/token