package com.sumec.project.dao;

import com.sumec.project.entity.TSubContract;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import java.math.BigDecimal;
import java.util.List;

/**
 * Created by daitiantian on 2017/11/16.
 */
public interface ISubContractDao {

    @Select({
            "select",
            "BC_ID, C_NO, M_DATE, C_TYPE, FCT_NO, FIRST_PARTY, PACK_TRM, QUALITY, QUALITY_TIME, ",
            "DEPATURE, NOTE, DELI_D, MARKET, P_QUANT, P_AMT, STATUS_PS, END_ID, ROHS_BZ, ",
            "YH, IS_VALID, DEP_NO, GROUP_NO, EMP_NO, EMP_NAME, MAKER_NO, MAKER_NAME, MODIFY_NO, ",
            "MODIFY_NAME, MODIFY_DATE, CHECK_NO, CHECK_NAME, CHECK_DATE, FROM_ID, SERV_TAG, ",
            "GOODS_SAMPLE, SAMPLE_GET, DOCS, CONFIRM, REASON, FP_AMT, PAY_AMT, WH_NO, N_NO, ",
            "REAL_NO, MANUAL_NO, PAY_TERM, OC_ID, IS_INSTALL, TAG, GJ_TERM, NEED_CALC, ACC_NO, ",
            "ORG_ID, USER_ID, CELL_ID, FCT_ID, KC_TYPE, VIEW_SCOPE, PROMPT, IS_NEED_SAMPLE, ",
            "IS_GET_SAMPLE, TRADEMODE, CURR_TYPE, PRO_ID, PRO_TYPE, SEND_OVER_TAG, SEND_OVER_DATE, ",
            "FCT_ORDER_NO, IS_JS_REAL, CHECK_USER_ID, MODIFY_USER_ID, COPY_PARTY_NO, COPY_PARTY_ID, ",
            "COPY_MOVE_NO, COPY_MOVE_ID, IS_JQ_OVER, UNDO, IS_ZY_OVER, PRODUCER_ID, PRODUCER_NO, ",
            "PRODUCER_NAME, GD_TAG, GD_USER_ID, GD_DATE, GJ_FCT_NO, GJ_FCT_ID, OCU_ORG_ID, ",
            "SEND_TERM, SEND_DAY, SENDOVER_DAY, SEND_DATE, SENDOVER_DATE, WH_ID, WH_NAME, ",
            "BC_TYPE, TRANS_WAY, SIGN_DATE, C_TERM, CST_SHORT_NAME, TRANS_CORP_ID, TRANS_CORP_NAME, ",
            "OTHER_REQ, IS_U8_PURCHARSE_REQ, IS_MOVE, IS_CLOSE, CLOSE_USER_ID, CLOSE_DATE, ",
            "IU_OCU_ID, INLAND_OR_OVERSEAS, TYPE_OF_CON, CLOSE_CONFIRM, DEP_ORG_ID, PURCHASER_ID, ",
            "CATA_OF_CON, PROP_OF_CON, BIZ_MODE, REL_BC_ID, CON_NAME, VALID_DATE, SIGN_PLACE, ",
            "CON_CONTENT, SELLER_NATION_ID, SELLER_PROP, SENDER_ID, LAND_NATION_ID, LAND_PORT_ID, ",
            "LAND_LOCATION, RECER_ID, DEST_NATION_ID, DEST_PORT_ID, DEST_LOCATION, IS_BATCHES, ",
            "IS_TRANSFER, TRANSFER_PORT_ID, COMMISSION_ID, COMMISSION_RATE, COMMISSION_CURR_TYPE, ",
            "COMMISSION_FEE, SHIPMENT_WAY, BOX_DELIVERY_TYPE, DELIVERY_PLACE, IS_PLAN_ST, ",
            "PROXY_CORP_ID, TRANS_RESP, TRANS_FEE_RESP, TRANS_INSU_RESP, ARBITRATION_PLACE, ",
            "SUE_PLACE, IS_NEED_SPEC_DOCU, PRICING_WAY, PRICE_STANDARD, EXAM_STANDARD, CON_PERIOD, ",
            "BAIL_RATE, PROFIT_SCHEME, COMM_QUANT_PACK, COMM_QUANT_STAT, C_STATUS, CMD_CATA_ID, ",
            "PRICE_TERM, FCT_NAME, PURCHASER_NAME, SENDER_NAME, RECER_NAME, COMMISSION_NAME, ",
            "PROXY_CORP_NAME, AFFECT_INCOME, AFFECT_INCOME_RATE, MANUFAC_ID, MANUFAC_NAME, ",
            "U8_OP_ID, CNY_RATE, USD_RATE, CURR_RATE, SHORT_OR_OVER, CON_PERIOD_S_TYPE, ",
            "COMM_UNIT",
            "from T_EXP_BC",
            "where PRO_ID = #{projId,jdbcType=DECIMAL}"
    })
    @ResultMap("com.sumec.project.dao.ISubContractDao.BaseResultMap")
    List<TSubContract> selectListByProjId(BigDecimal projId);

    @Select({
            "select",
            "BC_ID, C_NO, M_DATE, C_TYPE, FCT_NO, FIRST_PARTY, PACK_TRM, QUALITY, QUALITY_TIME, ",
            "DEPATURE, NOTE, DELI_D, MARKET, P_QUANT, P_AMT, STATUS_PS, END_ID, ROHS_BZ, ",
            "YH, IS_VALID, DEP_NO, GROUP_NO, EMP_NO, EMP_NAME, MAKER_NO, MAKER_NAME, MODIFY_NO, ",
            "MODIFY_NAME, MODIFY_DATE, CHECK_NO, CHECK_NAME, CHECK_DATE, FROM_ID, SERV_TAG, ",
            "GOODS_SAMPLE, SAMPLE_GET, DOCS, CONFIRM, REASON, FP_AMT, PAY_AMT, WH_NO, N_NO, ",
            "REAL_NO, MANUAL_NO, PAY_TERM, OC_ID, IS_INSTALL, TAG, GJ_TERM, NEED_CALC, ACC_NO, ",
            "ORG_ID, USER_ID, CELL_ID, FCT_ID, KC_TYPE, VIEW_SCOPE, PROMPT, IS_NEED_SAMPLE, ",
            "IS_GET_SAMPLE, TRADEMODE, CURR_TYPE, PRO_ID, PRO_TYPE, SEND_OVER_TAG, SEND_OVER_DATE, ",
            "FCT_ORDER_NO, IS_JS_REAL, CHECK_USER_ID, MODIFY_USER_ID, COPY_PARTY_NO, COPY_PARTY_ID, ",
            "COPY_MOVE_NO, COPY_MOVE_ID, IS_JQ_OVER, UNDO, IS_ZY_OVER, PRODUCER_ID, PRODUCER_NO, ",
            "PRODUCER_NAME, GD_TAG, GD_USER_ID, GD_DATE, GJ_FCT_NO, GJ_FCT_ID, OCU_ORG_ID, ",
            "SEND_TERM, SEND_DAY, SENDOVER_DAY, SEND_DATE, SENDOVER_DATE, WH_ID, WH_NAME, ",
            "BC_TYPE, TRANS_WAY, SIGN_DATE, C_TERM, CST_SHORT_NAME, TRANS_CORP_ID, TRANS_CORP_NAME, ",
            "OTHER_REQ, IS_U8_PURCHARSE_REQ, IS_MOVE, IS_CLOSE, CLOSE_USER_ID, CLOSE_DATE, ",
            "IU_OCU_ID, INLAND_OR_OVERSEAS, TYPE_OF_CON, CLOSE_CONFIRM, DEP_ORG_ID, PURCHASER_ID, ",
            "CATA_OF_CON, PROP_OF_CON, BIZ_MODE, REL_BC_ID, CON_NAME, VALID_DATE, SIGN_PLACE, ",
            "CON_CONTENT, SELLER_NATION_ID, SELLER_PROP, SENDER_ID, LAND_NATION_ID, LAND_PORT_ID, ",
            "LAND_LOCATION, RECER_ID, DEST_NATION_ID, DEST_PORT_ID, DEST_LOCATION, IS_BATCHES, ",
            "IS_TRANSFER, TRANSFER_PORT_ID, COMMISSION_ID, COMMISSION_RATE, COMMISSION_CURR_TYPE, ",
            "COMMISSION_FEE, SHIPMENT_WAY, BOX_DELIVERY_TYPE, DELIVERY_PLACE, IS_PLAN_ST, ",
            "PROXY_CORP_ID, TRANS_RESP, TRANS_FEE_RESP, TRANS_INSU_RESP, ARBITRATION_PLACE, ",
            "SUE_PLACE, IS_NEED_SPEC_DOCU, PRICING_WAY, PRICE_STANDARD, EXAM_STANDARD, CON_PERIOD, ",
            "BAIL_RATE, PROFIT_SCHEME, COMM_QUANT_PACK, COMM_QUANT_STAT, C_STATUS, CMD_CATA_ID, ",
            "PRICE_TERM, FCT_NAME, PURCHASER_NAME, SENDER_NAME, RECER_NAME, COMMISSION_NAME, ",
            "PROXY_CORP_NAME, AFFECT_INCOME, AFFECT_INCOME_RATE, MANUFAC_ID, MANUFAC_NAME, ",
            "U8_OP_ID, CNY_RATE, USD_RATE, CURR_RATE, SHORT_OR_OVER, CON_PERIOD_S_TYPE, ",
            "COMM_UNIT",
            "from T_EXP_BC",
            "where BC_ID = #{bcId,jdbcType=DECIMAL}"
    })
    @ResultMap("com.sumec.project.dao.ISubContractDao.BaseResultMap")
    TSubContract selectByPrimaryKey(BigDecimal bcId);

}
